function [A,B] = getAB(L,in2,in3)
%GETAB
%    [A,B] = GETAB(L,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2021 10:09:37

delta = in3(1,:);
theta = in2(3,:);
v = in3(2,:);
t2 = cos(theta);
t3 = tan(delta);
t4 = sin(theta);
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-t4.*v,t2.*v,0.0],[3,3]);
if nargout > 1
    t5 = 1.0./L;
    B = reshape([0.0,0.0,t5.*v.*(t3.^2+1.0),t2,t4,t3.*t5],[3,2]);
end
