function rts = getDeltaI2(phi,k1,s2,c2,k3)
%GETDELTAI2
%    RTS = GETDELTAI2(PHI,K1,S2,C2,K3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Apr-2021 17:57:04

rts = [(k1.*s2)./(c2.*k1-1.0);-(c2.*k1)./(k3-phi+k1.*s2);-(c2.*k1)./(k3+k1.*s2)];
