function rts = getDeltaI(phi,k1,s2,c2,k3,phi_d,phi_dot_d,phi_dot_dot_d)
%GETDELTAI
%    RTS = GETDELTAI(PHI,K1,S2,C2,K3,PHI_D,PHI_DOT_D,PHI_DOT_DOT_D)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Apr-2021 17:46:44

rts = [((c2.*k1+k1.*sqrt(c2.^3.*k1.*-2.0+c2.^2+c2.^4.*k1.^2+k1.^2.*s2.^4+k3.^2.*s2.^2+k1.*k3.*s2.^3.*2.0-c2.*k3.*s2.*2.0-c2.*phi_dot_d.*s2.*4.0-c2.*phi_dot_dot_d.*s2.*4.0+c2.^2.*k1.^2.*s2.^2.*2.0-c2.*k1.*s2.^2.*2.0+c2.^2.*k1.*k3.*s2.*2.0)-c2.^2.*k1.^2+k1.^2.*s2.^2+k1.*k3.*s2).*(-1.0./2.0))./(k3+phi_dot_d+phi_dot_dot_d+k1.*s2-c2.*k1.*k3-c2.*k1.^2.*s2);((c2.*k1-k1.*sqrt(c2.^3.*k1.*-2.0+c2.^2+c2.^4.*k1.^2+k1.^2.*s2.^4+k3.^2.*s2.^2+k1.*k3.*s2.^3.*2.0-c2.*k3.*s2.*2.0-c2.*phi_dot_d.*s2.*4.0-c2.*phi_dot_dot_d.*s2.*4.0+c2.^2.*k1.^2.*s2.^2.*2.0-c2.*k1.*s2.^2.*2.0+c2.^2.*k1.*k3.*s2.*2.0)-c2.^2.*k1.^2+k1.^2.*s2.^2+k1.*k3.*s2).*(-1.0./2.0))./(k3+phi_dot_d+phi_dot_dot_d+k1.*s2-c2.*k1.*k3-c2.*k1.^2.*s2);-(c2.*k1)./(k3-phi+phi_d+phi_dot_d+k1.*s2)];
