function [mt,mp,mi] = msFunc(delta_t,phi,delta_i)
%MSFUNC
%    [MT,MP,MI] = MSFUNC(DELTA_T,PHI,DELTA_I)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    03-Apr-2021 13:39:48

t2 = cos(delta_i);
t3 = tan(delta_t);
t4 = t3.^2;
t5 = 1.0./t2;
t6 = t3./4.0;
t7 = t4+1.6e+1;
t8 = atan(t6);
t9 = delta_i+phi+t8;
t11 = sqrt(t7);
t10 = cos(t9);
mt = (t5.*(t4+1.0).*(t10.*4.0-t2.*t11.*2.0+t3.*sin(t9)).*(-1.0./4.0))./t11;
if nargout > 1
    mp = t5.*t10.*t11.*(-1.0./4.0);
end
if nargout > 2
    mi = t5.^2.*t11.*cos(phi+t8).*(-1.0./4.0);
end
