function [A1,B1,A2,B2] = getABsplit(in1,in2,in3)
%GETABSPLIT
%    [A1,B1,A2,B2] = GETABSPLIT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2021 09:26:45

L_h = in1(2,:);
L_i = in1(3,:);
L_t = in1(1,:);
delta_i = in3(3,:);
delta_t = in3(2,:);
phi = in2(4,:);
theta_t = in2(3,:);
v = in3(1,:);
t2 = theta_t.*v;
t3 = L_h.^2;
t4 = L_t.^2;
t5 = delta_t.^2;
t6 = 1.0./L_i;
t7 = 1.0./L_t;
t8 = t5+1.0;
t9 = -t2;
A1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t9,v,0.0],[3,3]);
if nargout > 1
    t10 = L_h.*delta_t.*t7;
    t11 = t3.*t5;
    t12 = atan(t10);
    t13 = t7.*t8.*v;
    B1 = reshape([1.0,theta_t,delta_t.*t7,0.0,0.0,t13],[3,2]);
end
if nargout > 2
    t14 = t4+t11;
    t15 = sqrt(t14);
    A2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t9,v,0.0,0.0,0.0,0.0,0.0,0.0,t6.*t7.*t15.*v,0.0,0.0,0.0,t13,(t6.*t13.*(-L_i.*t15+L_h.*L_t+delta_i.*delta_t.*t3+delta_t.*phi.*t3+delta_t.*t3.*t12))./t15,0.0],[5,5]);
end
if nargout > 3
    B2 = [0.0;0.0;0.0;t6.*t7.*t15.*v.*(delta_i.*phi+delta_i.*t12+delta_i.^2+1.0);0.0];
end
