function [A,B] = getAB(in1,in2,in3)
%GETAB
%    [A,B] = GETAB(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2021 09:26:45

L_h = in1(2,:);
L_i = in1(3,:);
L_t = in1(1,:);
delta_i = in3(3,:);
delta_t = in3(2,:);
phi = in2(4,:);
theta_t = in2(3,:);
v = in3(1,:);
t2 = L_h.^2;
t3 = L_t.^2;
t4 = delta_t.^2;
t5 = 1.0./L_i;
t6 = 1.0./L_t;
t7 = t4+1.0;
t8 = delta_t.*t6;
t10 = t2.*t4;
t9 = L_h.*t8;
t12 = t3+t10;
t11 = atan(t9);
t13 = sqrt(t12);
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-theta_t.*v,v,0.0,0.0,0.0,0.0,0.0,t5.*t6.*t13.*v],[4,4]);
if nargout > 1
    B = reshape([1.0,theta_t,t8,-t8+t5.*t6.*t13.*(delta_i+phi+t11),0.0,0.0,t6.*t7.*v,(t5.*t6.*t7.*v.*(-L_i.*t13+L_h.*L_t+delta_i.*delta_t.*t2+delta_t.*phi.*t2+delta_t.*t2.*t11))./t13,0.0,0.0,0.0,t5.*t6.*t13.*v.*(delta_i.*phi+delta_i.*t11+delta_i.^2+1.0)],[4,3]);
end
